// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYF1vqNYYnZRv4BH9Zmx6oUWI0U8GOHV0',
    appId: '1:22263187420:web:48e12442b106e231ca7119',
    messagingSenderId: '22263187420',
    projectId: 'ghub-app',
    authDomain: 'ghub-app.firebaseapp.com',
    storageBucket: 'ghub-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1lviGf_A7oq-br6p0SwvKglaaS32VEA8',
    appId: '1:22263187420:android:5a4b9cc5713be96cca7119',
    messagingSenderId: '22263187420',
    projectId: 'ghub-app',
    storageBucket: 'ghub-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAcEAjY4vHVEOR7-DWH1Ibt7hNHOmpPlI',
    appId: '1:22263187420:ios:417c8d202e9dcba2ca7119',
    messagingSenderId: '22263187420',
    projectId: 'ghub-app',
    storageBucket: 'ghub-app.appspot.com',
    iosBundleId: 'com.example.ghubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAcEAjY4vHVEOR7-DWH1Ibt7hNHOmpPlI',
    appId: '1:22263187420:ios:a8f5ba503e8c995fca7119',
    messagingSenderId: '22263187420',
    projectId: 'ghub-app',
    storageBucket: 'ghub-app.appspot.com',
    iosBundleId: 'com.example.ghubApp.RunnerTests',
  );
}
